[package]
name = "circuit-psi"
version = "0.1.0"
edition = "2024"

[dependencies]
curve25519-dalek = "4"
rand_core = "0.10.0"
rand = "0.10.0"
anyhow = "1.0.102"
eyre = "0.6.12"
ff = { git = "https://github.com/GaloisInc/ff", rev = "1a4c6138e2e76e13f8d54fae81857e2cea3cbc4d", features = ["derive"] }
generic-array = "1.3.5"
lambdaworks-math = "0.13.0"
num-traits = "0.2.19"
rand08 = { package = "rand", version = "0.8.5" }
rayon = "1.11.0"
fourq = "0.1.6"
crypto-bigint = "0.5.5"
serde = { version = "1.0.228", features = ["derive"] }
subtle = "=2.5.0"
swanky-channel-legacy = { package = "scuttlebutt", path = "/home/ubuntu/.cargo/git/checkouts/swanky-5da08cbc633fe94e/553ede0/scuttlebutt" }
swanky-field-binary = { path = "/home/ubuntu/.cargo/git/checkouts/swanky-5da08cbc633fe94e/553ede0/crates/field-binary" }
swanky-field = { path = "/home/ubuntu/.cargo/git/checkouts/swanky-5da08cbc633fe94e/553ede0/crates/field" }
swanky-party = { path = "/home/ubuntu/.cargo/git/checkouts/swanky-5da08cbc633fe94e/553ede0/crates/party" }
swanky-serialization = { path = "/home/ubuntu/.cargo/git/checkouts/swanky-5da08cbc633fe94e/553ede0/crates/serialization" }
psi-aes = { path = "src/psi-aes" }
aes = "0.8.4"
p256 = "0.13.2"
clap = { version = "4.5.38", features = ["derive"] }

[[bin]]
name = "vole_cope"
path = "src/vole/bin/cope.rs"

[[bin]]
name = "mascot_unauthenticated_triple"
path = "src/mascot/bin/unauthenticated_triple.rs"

[profile.release]
lto = true
