[package]
name = "circuit-psi"
version = "0.1.0"
edition = "2024"

[dependencies]
curve25519-dalek = "4"
rand_core = "0.10.0"
rand = "0.10.0"
anyhow = "1.0.102"
eyre = "0.6.12"
ff = { path = "/home/ubuntu/.cargo/git/checkouts/ff-4a06948a8ccc4786/c29da06", features = ["derive"] }
generic-array = "1.3.5"
lambdaworks-math = "0.13.0"
num-traits = "0.2.19"
rand08 = { package = "rand", version = "0.8.5" }
rayon = "1.11.0"
fourq = "0.1.6"
crypto-bigint = { version = "0.6.1", features = ["hybrid-array"] }
serde = { version = "1.0.228", features = ["derive"] }
subtle = "2.6.1"
mac-n-cheese-vole = { path = "/home/ubuntu/.cargo/git/checkouts/swanky-5da08cbc633fe94e/50e0aba/edge/mac-n-cheese/vole" }
swanky-aes-rng = { path = "/home/ubuntu/.cargo/git/checkouts/swanky-5da08cbc633fe94e/50e0aba/edge/aes-rng" }
swanky-channel-legacy = { path = "/home/ubuntu/.cargo/git/checkouts/swanky-5da08cbc633fe94e/50e0aba/edge/channel-legacy" }
swanky-field-binary = { path = "/home/ubuntu/.cargo/git/checkouts/swanky-5da08cbc633fe94e/50e0aba/edge/field-binary" }
swanky-field = { path = "/home/ubuntu/.cargo/git/checkouts/swanky-5da08cbc633fe94e/50e0aba/edge/field" }
swanky-party = { path = "/home/ubuntu/.cargo/git/checkouts/swanky-5da08cbc633fe94e/50e0aba/edge/party" }
swanky-serialization = { path = "/home/ubuntu/.cargo/git/checkouts/swanky-5da08cbc633fe94e/50e0aba/edge/serialization" }
psi-aes = { path = "src/psi-aes" }
aes = "0.8.4"
p256 = "0.13.2"

[[bin]]
name = "vole_cope"
path = "src/vole/bin/cope.rs"

[[bin]]
name = "mascot_unauthenticated_triple"
path = "src/mascot/bin/unauthenticated_triple.rs"

[profile.release]
lto = true
