[package]
name = "circuit-psi"
version = "0.1.0"
edition = "2024"

[dependencies]
curve25519-dalek = "4"
rand_core = "0.10.0"
rand = "0.10.0"
anyhow = "1.0.101"
swanky-field-binary = { git = "https://github.com/GaloisInc/swanky", rev = "50e0abad78ee276449243dfc51f6202588bc68eb" }
swanky-serialization = { git = "https://github.com/GaloisInc/swanky", rev = "50e0abad78ee276449243dfc51f6202588bc68eb" }
swanky-field = { git = "https://github.com/GaloisInc/swanky", rev = "50e0abad78ee276449243dfc51f6202588bc68eb" }

[profile.release]
lto = true
