use crate::iknp::IKNP;
use crate::pre_ot::OTPre;
use psi_aes::prg::PRG;
use crate::comm_util::*;
use swanky_channel_legacy::AbstractChannel;

const NUM_BYTES: usize = 16; // NUM_BYTES is the message length generated by IKNP, which just needs to be large enough for security

// Generate COT of arbitrary message length, by hashing the ones generated from IKNP, and point-and-permute
pub struct BaseCot {
    party: usize, // Alice: 0, Bob: 1
    one: [u8; 16],
    minus_one: [u8; 16],
    ot_delta: Option<[u8; 16]>,
    iknp: IKNP,
    malicious: bool,
}

impl BaseCot {
    pub fn new(party: usize, malicious: bool) -> Self {
        let one = [
            1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        ]; // Little-endian representation of 1
        let minus_one = [
            254, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        ]; // Little-endian representation of u128::MAX - 1

        BaseCot {
            party,
            one,
            minus_one,
            ot_delta: None,
            iknp: IKNP::new(malicious),
            malicious,
        }
    }

    pub fn cot_gen_pre<IO: AbstractChannel>(&mut self, io: &mut IO, deltain: Option<[u8; 16]>, comm: &mut u64) {
        if let Some(deltain) = deltain {
            if self.party == 0 {
                self.ot_delta = Some(deltain);
                let delta_bool = block_to_bool(&deltain);
                self.iknp.setup_send(io, Some(&delta_bool), None, comm);
            } else {
                self.iknp.setup_recv(io, None, None, comm);
            }
        } else {
            if self.party == 0 {
                let mut prg = PRG::new(None, 0);
                let mut tmp = [[0u8; 16]];
                prg.random_16byte_block(&mut tmp);
                let mut delta = tmp[0];
                delta = bitwise_and(&delta, &self.minus_one);
                delta = bitwise_xor(&delta, &self.one); // To make sure delta has the last bit equals to 1
                self.ot_delta = Some(delta);
                let delta_bool = block_to_bool(&delta);
                self.iknp.setup_send(io, Some(&delta_bool), None, comm);
            } else {
                self.iknp.setup_recv(io, None, None, comm);
            }
        }
    }

    pub fn cot_gen<IO: AbstractChannel>(&mut self, io: &mut IO, ot_data: &mut [[u8; 16]], size: usize, pre_bool: Option<&[bool]>, comm: &mut u64) {
        if self.party == 0 {
            self.iknp.send_cot(io, ot_data, size, comm);
            io.flush();
            for block in ot_data.iter_mut() {
                *block = bitwise_and(block, &self.minus_one);
            }
        } else {
            let mut prg = PRG::new(None, 0);
            let mut pre_bool_ini = vec![false; size];
            if let Some(pre_bool) = pre_bool {
                if !self.malicious {
                    pre_bool_ini.copy_from_slice(pre_bool);
                } else {
                    prg.random_bool_array(&mut pre_bool_ini);
                }
            } else {
                prg.random_bool_array(&mut pre_bool_ini);
            }

            self.iknp.recv_cot(io, ot_data, &pre_bool_ini, size, comm);

            let ch = [
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
            ]; 

            for (i, block) in ot_data.iter_mut().enumerate() {
                *block = bitwise_xor(&bitwise_and(block, &self.minus_one), &ch[pre_bool_ini[i] as usize]);
            }
        }
    }

    pub fn cot_gen_preot<IO: AbstractChannel, const NUM_LIMBS: usize>(&mut self, io: &mut IO, pre_ot: &mut OTPre<NUM_LIMBS>, size: usize, pre_bool: Option<&[bool]>, comm: &mut u64) {
        let mut ot_data = vec![[0u8; 16]; size]; // Allocate space for `ot_data`

        if self.party == 0 {
            // ALICE
            self.iknp.send_cot(io, &mut ot_data, size, comm);
            // io.flush();

            // Apply `minus_one` to all blocks
            for block in ot_data.iter_mut() {
                *block = bitwise_and(block, &self.minus_one);
            }

            // Call `send_pre` on `pre_ot`
            if let Some(delta) = self.ot_delta {
                pre_ot.send_pre(&ot_data, delta);
            }
        } else {
            // BOB
            let mut prg = PRG::new(None, 0);
            let mut pre_bool_ini = vec![false; size];

            // Initialize `pre_bool_ini`
            if let Some(pre_bool) = pre_bool {
                if !self.malicious {
                    pre_bool_ini.copy_from_slice(pre_bool);
                } else {
                    prg.random_bool_array(&mut pre_bool_ini);
                }
            } else {
                prg.random_bool_array(&mut pre_bool_ini);
            }

            // Call `recv_cot` on `iknp`
            self.iknp.recv_cot(io, &mut ot_data, &pre_bool_ini, size, comm);

            let ch = [
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            ]; 

            // Modify `ot_data` based on `pre_bool_ini`
            for (i, block) in ot_data.iter_mut().enumerate() {
                *block = bitwise_xor(&bitwise_and(block, &self.minus_one), &ch[pre_bool_ini[i] as usize]);
            }

            // Call `recv_pre` on `pre_ot`
            pre_ot.recv_pre(&ot_data, Some(&pre_bool_ini));
        }
    }

    // Debugging check for COT
    pub fn check_cot<IO: AbstractChannel>(&mut self, io: &mut IO, data: &[[u8; 16]], len: usize) -> bool {
        if self.party == 0 {
            if let Some(delta) = self.ot_delta {
                send_block::<16>(io, &[delta]).expect("Failed to send delta");
            }
            send_block::<16>(io, data).expect("Failed to send check data");
            io.flush();
            true
        } else {
            let mut tmp = vec![[0u8; 16]; len];
            let mut ch = [[0u8; 16]; 2];
            ch[1] = receive_block::<16>(io).expect("Failed to receiver delta")[0];
            ch[0] = [0u8; 16];
            tmp = receive_block::<16>(io).expect("Failed to receive check data");
            for i in 0..len {
                tmp[i] = bitwise_xor(&tmp[i], &ch[get_lsb(&data[i]) as usize]);
            }
            cmp_blocks(&tmp, data)
        }
    }
}

fn block_to_bool(block: &[u8; 16]) -> [bool; 128] {
    let mut result = [false; 128];
    for (i, byte) in block.iter().enumerate() {
        for bit in 0..8 {
            result[i * 8 + bit] = (byte >> bit) & 1 != 0;
        }
    }
    result
}

fn get_lsb(block: &[u8; 16]) -> bool {
    block[0] & 1 != 0
}

fn cmp_blocks(a: &[[u8; 16]], b: &[[u8; 16]]) -> bool {
    a == b
}

fn bitwise_xor(a: &[u8; 16], b: &[u8; 16]) -> [u8; 16] {
    [
        a[0] ^ b[0], a[1] ^ b[1], a[2] ^ b[2], a[3] ^ b[3],
        a[4] ^ b[4], a[5] ^ b[5], a[6] ^ b[6], a[7] ^ b[7],
        a[8] ^ b[8], a[9] ^ b[9], a[10] ^ b[10], a[11] ^ b[11],
        a[12] ^ b[12], a[13] ^ b[13], a[14] ^ b[14], a[15] ^ b[15],
    ]
}

fn bitwise_and(a: &[u8; 16], b: &[u8; 16]) -> [u8; 16] {
    [
        a[0] & b[0], a[1] & b[1], a[2] & b[2], a[3] & b[3],
        a[4] & b[4], a[5] & b[5], a[6] & b[6], a[7] & b[7],
        a[8] & b[8], a[9] & b[9], a[10] & b[10], a[11] & b[11],
        a[12] & b[12], a[13] & b[13], a[14] & b[14], a[15] & b[15],
    ]
}